<a href="https://colab.research.google.com/github/rlmowrey/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPUs (vs regular CPUs).
*   Default data type is float32.
*   More suitable for deep learning than a Numpy Array.

In [3]:
import torch
import numpy as np

**LISTS**

In [5]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list[1][3]

9

**NUMPY ARRAYS**

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.13953392, 0.80822603, 0.08035879, 0.6438931 ],
       [0.23752202, 0.76180348, 0.48164386, 0.20176579],
       [0.66013145, 0.26538329, 0.34945976, 0.74231012]])

In [7]:
np1.dtype

dtype('float64')

**TENSORS**

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1226, -1.0313, -0.6595, -1.2915],
        [-0.9143,  0.3801,  0.1708, -0.0617],
        [ 0.7284, -0.0185, -0.1764,  0.1705]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1395, 0.8082, 0.0804, 0.6439],
        [0.2375, 0.7618, 0.4816, 0.2018],
        [0.6601, 0.2654, 0.3495, 0.7423]], dtype=torch.float64)